### ISSUE TITLE
Authentication page broken

### ISSUE THREAD

**Issue by jeffreymeng** [t485/t485#103]
Steps to reproduce:

1. navigate to the files page(https://www.t485.org/resources/files.html)
2. click on the red `Login with google` button
3. proceed to login page
4. you will be redirected to google to login.
5. Using an email address on the members list, the console will print out an object after a few seconds
6. The loading animation will continue, but nothing will happen(for the next 45 seconds on fast wifi network) then I navigated away from the page.

Additional Discussion Points:

1. Change loading page background to green?
2. Make the page more similar to rest of website's UI?
3. change text color to white or more visible color?

**Comment by richyliu** [comment]
@jeffreymeng Is there a specific commit(s) that triggered this bug? Please reference a specific commit(s) for easier fixing/debugging

**Comment by jeffreymeng** [comment]
no

**Comment by richyliu** [comment]
fixed by #104
