### ISSUE TITLE
Directory detailed view does not show all data

### ISSUE THREAD

**Issue by jeffkmeng** [t485/t485#124]
Data from Bug Report modal submitted by **Jeffrey Meng**:

| Timestamp | Device | Browser | Type |
|---|---|---|---|
| Thu Dec 13 2018 20:36:48 GMT-0800 (Pacific Standard Time) | Mac OS | Google Chrome | bug | 

**Affected pages**:
```https://beta.t485.org/directory?
```
![User uploaded image: https://firebasestorage.googleapis.com/v0/b/t485-main.appspot.com/o/feedback%2Fbug%2Ffiles%2F-LTf-9hEfNihiNAv87MK?alt=media&token=8156e4e2-15c4-4129-bcee-00492d3e4717](https://firebasestorage.googleapis.com/v0/b/t485-main.appspot.com/o/feedback%2Fbug%2Ffiles%2F-LTf-9hEfNihiNAv87MK?alt=media&token=8156e4e2-15c4-4129-bcee-00492d3e4717) 

 ------- 
When you click on a name, the modal that shows up lists a lot of data as not listed on spreadsheet, when it really has been listed.

 ------- 
This report automatically created from the [t485.org](https://t485.org) feedback form.

**Comment by jeffreymeng** [comment]
fixed
