### ISSUE TITLE
files page

### ISSUE THREAD

**Issue by sturdyoak2012** [t485/t485#93]
hi jeffrey can we clean up the files page
i think there are a lot miscellaneous files and it's hard to sort out what it is important and what is useless

**Comment by jeffreymeng** [comment]
Sure

**Comment by sturdyoak2012** [comment]
[Forest's Resume Teaching.pdf](https://github.com/t485/t485/files/1172198/Forest.s.Resume.Teaching.pdf)
Add forest's teaching please
